spring:
  datasource:
    url: jdbc:mysql://172.16.211.107:3306/benepick
    username: benepick
    password: benepick1234
    driver-class-name: com.mysql.cj.jdbc.Driver



springdoc:
  api-docs:
    enabled: true
    path: '/api-docs'
  swagger-ui:
    path: '/swagger'