spring:
  datasource:
    url: jdbc:mysql://61.109.238.197:3306/benepick
    username: ${DB_USERNAME:benepick} # 환경 변수 사용
    password: ${DB_PASSWORD:benepick1234} # 환경 변수 사용
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # 엔티티 변경을 데이터베이스 스키마에 자동 반영
    show-sql: true # 콘솔에 SQL 로그를 표시
    generate-ddl: true # DDL을 자동 생성
    properties:
      hibernate:
        format_sql: true # SQL 로그를 보기 좋게 포맷
        default_batch_fetch_size: 100 # IN 쿼리의 최대 개수
        dialect: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  redis:
    host: ${REDIS_HOST:61.109.239.241} # 환경 변수 사용
    port: ${REDIS_PORT:20006} # 환경 변수 사용
    password: ${REDIS_PASSWORD:benepick1234} # 환경 변수 사용

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    path: /swagger

jwt:
  secretKey: ${JWT_SECRET_KEY:01254cd9f9f67bab5529f1d210a20d93eab0aa9d09d681e3b201b36a4069fd6b} # 환경 변수 사용
  access:
    expiration: 360000000000 # 1시간(60분)
  refresh:
    expiration: 12096000000000 # 2주

cloud:
  kakao:
    object-storage:
      endpoint: https://objectstorage.kr-central-2.kakaocloud.com
      region: kr-central-2
      bucket: benepick-bucket
      access-key: ${KAKAO_CLOUD_ACCESS_KEY:893127421f0b43799dbb7daac5f9d976} # 환경 변수 사용
      secret-key: ${KAKAO_CLOUD_SECRET_KEY:355f9de08450494591d10b858fac34f9} # 환경 변수 사용
      project-id : 627e0b3fc53c4793b30520a51de16438

kakao-work:
  token: ${KAKAO_WORK_TOKEN:f8fa2df6.0e614e5f77a8477f8ec40dc1d6e9b393} # 환경 변수 사용

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true

server:
  port: 8443
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore.p12
    key-store-password: ${KEYSTORE_PASSWORD:benepick1234} # 환경 변수 사용
    